kind: pipeline
type: docker
name: mushroom-classification-frontend-pipeline

steps: 
- name: build-and-test-and-lint
  image: node:14.7.0-alpine
  environment:
    DOTENVS:
      from_secret: DOTENVS
  commands:
    - yarn
    - echo "$DOTENVS" > ./.env
    # temporary disable tests as VPS is running out of memory when running tests
    # not much point upgrading my VPS just to run a pipeline for two
    # apps which I've finished working on
    # - yarn jest --coverage
    # - yarn build
    - yarn lint --format checkstyle

- name: publish-docker-image  
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhubusername
    password:
      from_secret: dockerhubpassword
    repo:
      from_secret: dockerhubimage
  auto_tag: true
  when:
    branch:
    - master